### ISSUE TITLE
How to set target system to RTL8196C?

### ISSUE THREAD

**Issue by pixelein** [hkwi/openwrt-realtek#1]
Hi, there

I used "make menuconfig" and I saw the target system set to AR7xxx/AR9xxx by default. I didn't find RTL8196C at the list of target systems. How to compile openwrt-realtek for RTL8196C?

**Comment by hkwi** [comment]
checkout realtek branch

**Comment by hafo821** [comment]
I´ve got the same problem!Fuck

**Comment by hafo821** [comment]
You have to "git checkout realtek-unstable"

check this out!

http://archive.main.lv/writeup/building_openwrt_for_rtl8196c.html

**Comment by pixelein** [comment]
Thank you!
